export const enum GrapeType {
    CHARDONNAY = 'CHARDONNAY',
    SAUVIGNON_BLANC = 'SAUVIGNON_BLANC',
    SYRAH = 'SYRAH',
    CABERNET_SAUVIGNON = 'CABERNET_SAUVIGNON',
    CABERNET_FRANC = 'CABERNET_FRANC',
    MERLOT = 'MERLOT',
    PINOT_NOIR = 'PINOT_NOIR',
    RIESLING = 'RIESLING',
    MUSCAT = 'MUSCAT',
}
