spring:
  application:
    name: winebuddy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/winebuddy
    username: winebuddy
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    validate-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8080
springdoc:
  swagger-ui:
    url: /v3/api-docs
minio:
  url: http://localhost:9000
  bucketName: winebuddy-bucket
  accessKey: winebuddy
  accessSecret: password